import * as fs from "fs";
import * as path from "path";
import chalk from "chalk";

export interface InitOptions {
  dir?: string;
  python?: boolean;
}

interface ProjectInfo {
  dir: string;
  hasPackageJson: boolean;
  hasTsConfig: boolean;
  isPython: boolean;
  framework: "express" | "fastapi" | "flask" | "django" | null;
  entryFile: string | null;
  packageJson: Record<string, unknown> | null;
  tsConfig: Record<string, unknown> | null;
}

function detectProject(dir: string, forcePython: boolean): ProjectInfo {
  const info: ProjectInfo = {
    dir,
    hasPackageJson: false,
    hasTsConfig: false,
    isPython: forcePython,
    framework: null,
    entryFile: null,
    packageJson: null,
    tsConfig: null,
  };

  // Check for package.json
  const pkgPath = path.join(dir, "package.json");
  if (fs.existsSync(pkgPath)) {
    info.hasPackageJson = true;
    try {
      info.packageJson = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    } catch {
      // ignore parse errors
    }
  }

  // Check for tsconfig.json
  const tsPath = path.join(dir, "tsconfig.json");
  if (fs.existsSync(tsPath)) {
    info.hasTsConfig = true;
    try {
      // Strip comments (simple approach: remove // and /* */ comments)
      const raw = fs.readFileSync(tsPath, "utf-8");
      const cleaned = raw
        .replace(/\/\/.*$/gm, "")
        .replace(/\/\*[\s\S]*?\*\//g, "");
      info.tsConfig = JSON.parse(cleaned);
    } catch {
      // ignore parse errors
    }
  }

  // Check for Python project
  if (
    fs.existsSync(path.join(dir, "pyproject.toml")) ||
    fs.existsSync(path.join(dir, "setup.py")) ||
    fs.existsSync(path.join(dir, "requirements.txt"))
  ) {
    info.isPython = true;
  }

  // Detect framework from dependencies
  if (info.packageJson) {
    const deps = {
      ...(info.packageJson.dependencies as Record<string, string> | undefined),
      ...(info.packageJson.devDependencies as Record<string, string> | undefined),
    };
    if (deps.express) info.framework = "express";
  }

  if (info.isPython) {
    // Check requirements.txt or pyproject.toml for framework
    const reqPath = path.join(dir, "requirements.txt");
    if (fs.existsSync(reqPath)) {
      const reqs = fs.readFileSync(reqPath, "utf-8").toLowerCase();
      if (reqs.includes("fastapi")) info.framework = "fastapi";
      else if (reqs.includes("flask")) info.framework = "flask";
      else if (reqs.includes("django")) info.framework = "django";
    }
  }

  // Detect entry file
  if (info.packageJson) {
    const main = info.packageJson.main as string | undefined;
    if (main && fs.existsSync(path.join(dir, main))) {
      info.entryFile = main;
    } else {
      // Common entry points
      for (const candidate of ["src/index.ts", "src/index.js", "index.ts", "index.js", "app.ts", "app.js", "server.ts", "server.js"]) {
        if (fs.existsSync(path.join(dir, candidate))) {
          info.entryFile = candidate;
          break;
        }
      }
    }
  }

  if (info.isPython && !info.entryFile) {
    for (const candidate of ["app.py", "main.py", "server.py", "wsgi.py"]) {
      if (fs.existsSync(path.join(dir, candidate))) {
        info.entryFile = candidate;
        break;
      }
    }
  }

  return info;
}

function createTrickleConfig(dir: string, info: ProjectInfo): boolean {
  const configPath = path.join(dir, ".tricklerc.json");
  if (fs.existsSync(configPath)) return false;

  // Also check for package.json "trickle" field
  if (info.packageJson && (info.packageJson as Record<string, unknown>).trickle) {
    return false;
  }

  const config: Record<string, unknown> = {};

  // Suggest stubs directory based on project structure
  if (fs.existsSync(path.join(dir, "src"))) {
    config.stubs = "src/";
  } else {
    config.stubs = ".";
  }

  // Default exclude patterns
  config.exclude = ["node_modules", "dist", "build", "__pycache__"];

  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf-8");
  return true;
}

function ensureTrickleDir(dir: string): string {
  const trickleDir = path.join(dir, ".trickle");
  if (!fs.existsSync(trickleDir)) {
    fs.mkdirSync(trickleDir, { recursive: true });
  }
  return trickleDir;
}

function writeInitialTypes(trickleDir: string, isPython: boolean): void {
  if (isPython) {
    const pyPath = path.join(trickleDir, "types.pyi");
    if (!fs.existsSync(pyPath)) {
      fs.writeFileSync(
        pyPath,
        [
          "# Auto-generated by trickle from runtime type observations",
          "# Run your app to populate types, then: trickle codegen --python --out .trickle/types.pyi",
          "#",
          "# This file will be updated automatically when using: trickle codegen --python --watch --out .trickle/types.pyi",
          "",
          "from typing import TypedDict",
          "",
          "# Types will appear here after your app processes its first requests.",
          "",
        ].join("\n"),
        "utf-8",
      );
    }
  } else {
    const tsPath = path.join(trickleDir, "types.d.ts");
    if (!fs.existsSync(tsPath)) {
      fs.writeFileSync(
        tsPath,
        [
          "// Auto-generated by trickle from runtime type observations",
          "// Run your app to populate types, then: trickle codegen --out .trickle/types.d.ts",
          "//",
          "// This file will be updated automatically when using: trickle codegen --watch --out .trickle/types.d.ts",
          "",
          "// Types will appear here after your app processes its first requests.",
          "",
        ].join("\n"),
        "utf-8",
      );
    }

    // Also create an api-client placeholder
    const clientPath = path.join(trickleDir, "api-client.ts");
    if (!fs.existsSync(clientPath)) {
      fs.writeFileSync(
        clientPath,
        [
          "// Auto-generated typed API client by trickle",
          "// Run your app to populate types, then: trickle codegen --client --out .trickle/api-client.ts",
          "",
          "// A fully-typed fetch client will appear here after your app serves its first API requests.",
          "",
        ].join("\n"),
        "utf-8",
      );
    }
  }
}

function updateTsConfig(dir: string, info: ProjectInfo): boolean {
  const tsConfigPath = path.join(dir, "tsconfig.json");

  if (!info.hasTsConfig || !info.tsConfig) {
    // No tsconfig — create a minimal one that includes .trickle
    if (!info.isPython) {
      const newConfig = {
        compilerOptions: {
          target: "ES2022",
          module: "commonjs",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: "./dist",
          rootDir: "./src",
        },
        include: ["src", ".trickle"],
      };
      fs.writeFileSync(tsConfigPath, JSON.stringify(newConfig, null, 2) + "\n", "utf-8");
      return true;
    }
    return false;
  }

  // Read the raw file to preserve formatting as much as possible
  const raw = fs.readFileSync(tsConfigPath, "utf-8");
  const config = info.tsConfig;

  // Check if .trickle is already included
  const include = config.include as string[] | undefined;
  if (include && include.some((p: string) => p === ".trickle" || p.startsWith(".trickle/"))) {
    return false; // Already configured
  }

  // Add .trickle to include array
  if (include) {
    include.push(".trickle");
  } else {
    (config as Record<string, unknown>).include = ["src", ".trickle"];
  }

  fs.writeFileSync(tsConfigPath, JSON.stringify(config, null, 2) + "\n", "utf-8");
  return true;
}

function updatePackageJson(dir: string, info: ProjectInfo): { scriptsAdded: string[] } {
  if (!info.hasPackageJson || !info.packageJson) {
    return { scriptsAdded: [] };
  }

  const pkgPath = path.join(dir, "package.json");
  const pkg = info.packageJson;
  const scripts = (pkg.scripts as Record<string, string>) || {};
  const added: string[] = [];

  // Add trickle:dev script for watch mode
  if (!scripts["trickle:dev"]) {
    const outFile = info.isPython ? ".trickle/types.pyi" : ".trickle/types.d.ts";
    const langFlag = info.isPython ? " --python" : "";
    scripts["trickle:dev"] = `trickle codegen${langFlag} --watch --out ${outFile}`;
    added.push("trickle:dev");
  }

  // Add trickle:client script for API client generation
  if (!info.isPython && !scripts["trickle:client"]) {
    scripts["trickle:client"] = "trickle codegen --client --out .trickle/api-client.ts";
    added.push("trickle:client");
  }

  // Add trickle:mock script
  if (!scripts["trickle:mock"]) {
    scripts["trickle:mock"] = "trickle mock";
    added.push("trickle:mock");
  }

  // Detect current start script and create a trickle-wrapped version
  const startScript = scripts.start || scripts.dev;
  if (startScript && !scripts["trickle:start"]) {
    // Check if it's a node command we can add -r to
    if (startScript.match(/\bnode\s/)) {
      scripts["trickle:start"] = startScript.replace(/\bnode\s/, "node -r trickle/register ");
      added.push("trickle:start");
    } else if (startScript.match(/\bts-node\s/)) {
      scripts["trickle:start"] = startScript.replace(/\bts-node\s/, "ts-node -r trickle/register ");
      added.push("trickle:start");
    } else if (startScript.match(/\bnodemon\s/)) {
      scripts["trickle:start"] = startScript.replace(/\bnodemon\s/, "nodemon -r trickle/register ");
      added.push("trickle:start");
    }
  }

  if (added.length > 0) {
    pkg.scripts = scripts;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");
  }

  return { scriptsAdded: added };
}

function updateGitignore(dir: string): boolean {
  const giPath = path.join(dir, ".gitignore");
  let content = "";

  if (fs.existsSync(giPath)) {
    content = fs.readFileSync(giPath, "utf-8");
    if (content.includes(".trickle")) {
      return false; // Already has it
    }
  }

  const addition = content.endsWith("\n") || content === ""
    ? ".trickle/\n"
    : "\n.trickle/\n";

  fs.writeFileSync(giPath, content + addition, "utf-8");
  return true;
}

export async function initCommand(opts: InitOptions): Promise<void> {
  const dir = path.resolve(opts.dir || ".");

  console.log("");
  console.log(chalk.bold("  trickle init"));
  console.log("");

  // Step 1: Detect project
  const info = detectProject(dir, opts.python === true);

  if (!info.hasPackageJson && !info.isPython) {
    console.log(chalk.yellow("  No package.json or Python project detected."));
    console.log(chalk.gray("  Run this command from your project root.\n"));
    process.exit(1);
  }

  const lang = info.isPython ? "Python" : "Node.js";
  console.log(chalk.gray(`  Detected: ${lang} project${info.framework ? ` (${info.framework})` : ""}`));
  if (info.entryFile) {
    console.log(chalk.gray(`  Entry: ${info.entryFile}`));
  }
  console.log("");

  // Step 2: Create .tricklerc.json
  const configCreated = createTrickleConfig(dir, info);
  if (configCreated) {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".tricklerc.json")} — project config`);
  } else {
    console.log(`  ${chalk.gray("-")} .tricklerc.json already exists`);
  }

  // Step 3: Create .trickle directory
  const trickleDir = ensureTrickleDir(dir);
  console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/")} directory`);

  // Step 3: Write initial type files
  writeInitialTypes(trickleDir, info.isPython);
  if (info.isPython) {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/types.pyi")} (type stubs)`);
  } else {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/types.d.ts")} (type declarations)`);
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/api-client.ts")} (typed API client)`);
  }

  // Step 4: Update tsconfig.json
  if (!info.isPython) {
    const tsUpdated = updateTsConfig(dir, info);
    if (tsUpdated) {
      if (info.hasTsConfig) {
        console.log(`  ${chalk.green("~")} Updated ${chalk.bold("tsconfig.json")} — added .trickle to include`);
      } else {
        console.log(`  ${chalk.green("+")} Created ${chalk.bold("tsconfig.json")} with .trickle included`);
      }
    } else {
      console.log(`  ${chalk.gray("-")} tsconfig.json already includes .trickle`);
    }
  }

  // Step 5: Update package.json scripts
  if (info.hasPackageJson) {
    const { scriptsAdded } = updatePackageJson(dir, info);
    if (scriptsAdded.length > 0) {
      for (const name of scriptsAdded) {
        console.log(`  ${chalk.green("+")} Added npm script: ${chalk.bold(name)}`);
      }
    }
  }

  // Step 6: Update .gitignore
  const giUpdated = updateGitignore(dir);
  if (giUpdated) {
    console.log(`  ${chalk.green("~")} Updated ${chalk.bold(".gitignore")} — added .trickle/`);
  }

  // Step 7: Print next steps
  console.log("");
  console.log(chalk.bold("  Next steps:"));
  console.log("");

  const entryFile = info.entryFile || (info.isPython ? "app.py" : "app.js");
  console.log(chalk.white("  1. Run your app with trickle (one command does everything):"));
  console.log(chalk.cyan(`     trickle run ${entryFile}`));
  console.log("");
  console.log(chalk.white("  2. That's it! trickle auto-detects the runtime, observes types,"));
  console.log(chalk.white("     and generates stubs from .tricklerc.json settings."));
  console.log("");
  console.log(chalk.gray("  Customize .tricklerc.json:"));
  console.log(chalk.gray('     { "stubs": "src/", "annotate": "src/", "exclude": ["test"] }'));
  console.log("");
  console.log(chalk.gray("  Other commands:"));
  console.log(chalk.gray("     trickle functions         — list observed functions"));
  console.log(chalk.gray("     trickle types <name>      — see types + sample data"));
  console.log(chalk.gray("     trickle annotate src/     — add type annotations to source files"));

  console.log("");
}
