import * as fs from "fs";
import * as path from "path";
import chalk from "chalk";

export interface InitOptions {
  dir?: string;
  python?: boolean;
}

interface ProjectInfo {
  dir: string;
  hasPackageJson: boolean;
  hasTsConfig: boolean;
  isPython: boolean;
  framework: "express" | "next" | "remix" | "vite" | "fastapi" | "flask" | "django" | null;
  entryFile: string | null;
  packageJson: Record<string, unknown> | null;
  tsConfig: Record<string, unknown> | null;
}

function detectProject(dir: string, forcePython: boolean): ProjectInfo {
  const info: ProjectInfo = {
    dir,
    hasPackageJson: false,
    hasTsConfig: false,
    isPython: forcePython,
    framework: null,
    entryFile: null,
    packageJson: null,
    tsConfig: null,
  };

  // Check for package.json
  const pkgPath = path.join(dir, "package.json");
  if (fs.existsSync(pkgPath)) {
    info.hasPackageJson = true;
    try {
      info.packageJson = JSON.parse(fs.readFileSync(pkgPath, "utf-8"));
    } catch {
      // ignore parse errors
    }
  }

  // Check for tsconfig.json
  const tsPath = path.join(dir, "tsconfig.json");
  if (fs.existsSync(tsPath)) {
    info.hasTsConfig = true;
    try {
      // Strip comments but preserve glob patterns like /**/*.ts
      const raw = fs.readFileSync(tsPath, "utf-8");
      // Only strip // comments that are NOT inside strings
      // And /* */ comments that are NOT inside strings (careful with globs)
      const cleaned = raw
        .replace(/\/\/.*$/gm, "")
        .replace(/("[^"]*")|\/\*[\s\S]*?\*\//g, (match, str) => str || "");
      info.tsConfig = JSON.parse(cleaned);
    } catch {
      // ignore parse errors
    }
  }

  // Check for Python project
  if (
    fs.existsSync(path.join(dir, "pyproject.toml")) ||
    fs.existsSync(path.join(dir, "setup.py")) ||
    fs.existsSync(path.join(dir, "requirements.txt"))
  ) {
    info.isPython = true;
  }

  // Detect framework from dependencies
  if (info.packageJson) {
    const deps = {
      ...(info.packageJson.dependencies as Record<string, string> | undefined),
      ...(info.packageJson.devDependencies as Record<string, string> | undefined),
    };
    if (deps.next) info.framework = "next";
    else if (deps['@remix-run/react'] || deps['@remix-run/dev']) info.framework = "remix";
    else if (deps.vite) info.framework = "vite";
    else if (deps.express) info.framework = "express";
  }

  if (info.isPython) {
    // Check requirements.txt or pyproject.toml for framework
    const reqPath = path.join(dir, "requirements.txt");
    if (fs.existsSync(reqPath)) {
      const reqs = fs.readFileSync(reqPath, "utf-8").toLowerCase();
      if (reqs.includes("fastapi")) info.framework = "fastapi";
      else if (reqs.includes("flask")) info.framework = "flask";
      else if (reqs.includes("django")) info.framework = "django";
    }
  }

  // Detect entry file
  if (info.packageJson) {
    const main = info.packageJson.main as string | undefined;
    if (main && fs.existsSync(path.join(dir, main))) {
      info.entryFile = main;
    } else {
      // Common entry points
      for (const candidate of ["src/index.ts", "src/index.js", "index.ts", "index.js", "app.ts", "app.js", "server.ts", "server.js"]) {
        if (fs.existsSync(path.join(dir, candidate))) {
          info.entryFile = candidate;
          break;
        }
      }
    }
  }

  if (info.isPython && !info.entryFile) {
    for (const candidate of ["app.py", "main.py", "server.py", "wsgi.py"]) {
      if (fs.existsSync(path.join(dir, candidate))) {
        info.entryFile = candidate;
        break;
      }
    }
  }

  return info;
}

function createTrickleConfig(dir: string, info: ProjectInfo): boolean {
  const configPath = path.join(dir, ".tricklerc.json");
  if (fs.existsSync(configPath)) return false;

  // Also check for package.json "trickle" field
  if (info.packageJson && (info.packageJson as Record<string, unknown>).trickle) {
    return false;
  }

  const config: Record<string, unknown> = {};

  // Suggest stubs directory based on project structure
  if (fs.existsSync(path.join(dir, "src"))) {
    config.stubs = "src/";
  } else {
    config.stubs = ".";
  }

  // Default exclude patterns
  config.exclude = ["node_modules", "dist", "build", "__pycache__"];

  fs.writeFileSync(configPath, JSON.stringify(config, null, 2) + "\n", "utf-8");
  return true;
}

function ensureTrickleDir(dir: string): string {
  const trickleDir = path.join(dir, ".trickle");
  if (!fs.existsSync(trickleDir)) {
    fs.mkdirSync(trickleDir, { recursive: true });
  }
  return trickleDir;
}

function writeInitialTypes(trickleDir: string, isPython: boolean): void {
  if (isPython) {
    const pyPath = path.join(trickleDir, "types.pyi");
    if (!fs.existsSync(pyPath)) {
      fs.writeFileSync(
        pyPath,
        [
          "# Auto-generated by trickle from runtime type observations",
          "# Run your app to populate types, then: trickle codegen --python --out .trickle/types.pyi",
          "#",
          "# This file will be updated automatically when using: trickle codegen --python --watch --out .trickle/types.pyi",
          "",
          "from typing import TypedDict",
          "",
          "# Types will appear here after your app processes its first requests.",
          "",
        ].join("\n"),
        "utf-8",
      );
    }
  } else {
    const tsPath = path.join(trickleDir, "types.d.ts");
    if (!fs.existsSync(tsPath)) {
      fs.writeFileSync(
        tsPath,
        [
          "// Auto-generated by trickle from runtime type observations",
          "// Run your app to populate types, then: trickle codegen --out .trickle/types.d.ts",
          "//",
          "// This file will be updated automatically when using: trickle codegen --watch --out .trickle/types.d.ts",
          "",
          "// Types will appear here after your app processes its first requests.",
          "",
        ].join("\n"),
        "utf-8",
      );
    }

    // Also create an api-client placeholder
    const clientPath = path.join(trickleDir, "api-client.ts");
    if (!fs.existsSync(clientPath)) {
      fs.writeFileSync(
        clientPath,
        [
          "// Auto-generated typed API client by trickle",
          "// Run your app to populate types, then: trickle codegen --client --out .trickle/api-client.ts",
          "",
          "// A fully-typed fetch client will appear here after your app serves its first API requests.",
          "",
        ].join("\n"),
        "utf-8",
      );
    }
  }
}

function updateTsConfig(dir: string, info: ProjectInfo): boolean {
  const tsConfigPath = path.join(dir, "tsconfig.json");

  if (!info.hasTsConfig) {
    // No tsconfig — create a minimal one that includes .trickle
    if (!info.isPython) {
      const newConfig = {
        compilerOptions: {
          target: "ES2022",
          module: "commonjs",
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          outDir: "./dist",
          rootDir: "./src",
        },
        include: ["src", ".trickle"],
      };
      fs.writeFileSync(tsConfigPath, JSON.stringify(newConfig, null, 2) + "\n", "utf-8");
      return true;
    }
    return false;
  }

  // Use text-based insertion to preserve formatting and glob patterns
  // (JSON.parse + stringify corrupts /**/ globs by treating them as comments)
  const raw = fs.readFileSync(tsConfigPath, "utf-8");

  // Check if .trickle is already included
  if (raw.includes(".trickle")) return false;

  // Find the "include" array and insert ".trickle" at the end
  const includeMatch = raw.match(/"include"\s*:\s*\[([^\]]*)\]/);
  if (includeMatch) {
    const bracket = includeMatch.index! + includeMatch[0].length - 1; // position of ]
    const inside = includeMatch[1];
    // Detect if it's single-line or multi-line
    if (inside.includes("\n")) {
      // Multi-line — add before the closing bracket with same indentation
      const lastEntry = inside.match(/.*\S[^\n]*/g);
      const indent = lastEntry ? lastEntry[lastEntry.length - 1].match(/^(\s*)/)?.[1] || "        " : "        ";
      const updated = raw.slice(0, bracket) + `,\n${indent}".trickle"` + raw.slice(bracket);
      fs.writeFileSync(tsConfigPath, updated, "utf-8");
    } else {
      // Single-line: ["src/**/*.ts", "tmp/**/*.ts"] → add ".trickle"
      const updated = raw.slice(0, bracket) + ', ".trickle"' + raw.slice(bracket);
      fs.writeFileSync(tsConfigPath, updated, "utf-8");
    }
    return true;
  }

  // No include array — add one after compilerOptions closing brace
  const compilerEnd = raw.match(/"compilerOptions"\s*:\s*\{/);
  if (compilerEnd) {
    // Find the closing brace of compilerOptions
    const startBrace = raw.indexOf("{", compilerEnd.index! + compilerEnd[0].length - 1);
    let depth = 1;
    let pos = startBrace + 1;
    while (pos < raw.length && depth > 0) {
      if (raw[pos] === "{") depth++;
      else if (raw[pos] === "}") depth--;
      pos++;
    }
    // pos is now right after the closing brace of compilerOptions
    const updated = raw.slice(0, pos) + `,\n    "include": ["src", ".trickle"]` + raw.slice(pos);
    fs.writeFileSync(tsConfigPath, updated, "utf-8");
    return true;
  }

  return false;
}

function updatePackageJson(dir: string, info: ProjectInfo): { scriptsAdded: string[] } {
  if (!info.hasPackageJson || !info.packageJson) {
    return { scriptsAdded: [] };
  }

  const pkgPath = path.join(dir, "package.json");
  const pkg = info.packageJson;
  const scripts = (pkg.scripts as Record<string, string>) || {};
  const added: string[] = [];

  // Add trickle:dev script for watch mode
  if (!scripts["trickle:dev"]) {
    const outFile = info.isPython ? ".trickle/types.pyi" : ".trickle/types.d.ts";
    const langFlag = info.isPython ? " --python" : "";
    scripts["trickle:dev"] = `trickle codegen${langFlag} --watch --out ${outFile}`;
    added.push("trickle:dev");
  }

  // Add trickle:client script for API client generation
  if (!info.isPython && !scripts["trickle:client"]) {
    scripts["trickle:client"] = "trickle codegen --client --out .trickle/api-client.ts";
    added.push("trickle:client");
  }

  // Add trickle:mock script
  if (!scripts["trickle:mock"]) {
    scripts["trickle:mock"] = "trickle mock";
    added.push("trickle:mock");
  }

  // Detect current start script and create a trickle-wrapped version
  const startScript = scripts.start || scripts.dev;
  if (startScript && !scripts["trickle:start"]) {
    // Check if it's a node command we can add -r to
    if (startScript.match(/\bnode\s/)) {
      scripts["trickle:start"] = startScript.replace(/\bnode\s/, "node -r trickle-observe/register ");
      added.push("trickle:start");
    } else if (startScript.match(/\bts-node\s/)) {
      scripts["trickle:start"] = startScript.replace(/\bts-node\s/, "ts-node -r trickle-observe/register ");
      added.push("trickle:start");
    } else if (startScript.match(/\bnodemon\s/)) {
      scripts["trickle:start"] = startScript.replace(/\bnodemon\s/, "nodemon -r trickle-observe/register ");
      added.push("trickle:start");
    }
  }

  if (added.length > 0) {
    pkg.scripts = scripts;
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n", "utf-8");
  }

  return { scriptsAdded: added };
}

function updateVitestConfig(dir: string): boolean {
  // Look for vitest.config.ts, vitest.config.js, vitest.config.mts, vite.config.ts, vite.config.js
  const candidates = [
    "vitest.config.ts",
    "vitest.config.js",
    "vitest.config.mts",
    "vite.config.ts",
    "vite.config.js",
  ];

  let configFile: string | null = null;
  for (const c of candidates) {
    if (fs.existsSync(path.join(dir, c))) {
      configFile = c;
      break;
    }
  }

  if (!configFile) return false;

  const configPath = path.join(dir, configFile);
  const content = fs.readFileSync(configPath, "utf-8");

  // Already has tricklePlugin
  if (content.includes("tricklePlugin")) return false;

  // Find the import section end and plugins array
  const lines = content.split("\n");
  let lastImportLine = -1;
  let pluginsLine = -1;
  let pluginsArrayContent = "";

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i];
    if (/^\s*import\s/.test(line)) {
      // Track multi-line imports
      lastImportLine = i;
      if (!line.includes(";") && !line.includes("from")) {
        // Multi-line import — find the closing line
        for (let j = i + 1; j < lines.length; j++) {
          if (lines[j].includes("from")) {
            lastImportLine = j;
            break;
          }
        }
      }
    }
    if (/plugins\s*:\s*\[/.test(line)) {
      pluginsLine = i;
      pluginsArrayContent = line;
    }
  }

  if (lastImportLine === -1) return false;

  // Add import after last import
  const importLine = `import { tricklePlugin } from "trickle-observe/vite-plugin";`;
  lines.splice(lastImportLine + 1, 0, importLine);

  // Adjust pluginsLine index since we inserted a line
  if (pluginsLine > lastImportLine) {
    pluginsLine += 1;
  }

  // Add tricklePlugin() to plugins array
  if (pluginsLine !== -1) {
    const line = lines[pluginsLine];
    // Check if plugins array is on one line: plugins: [something()],
    if (/plugins\s*:\s*\[.*\]/.test(line)) {
      // Insert tricklePlugin() before the closing bracket
      lines[pluginsLine] = line.replace(/\]/, ", tricklePlugin()]");
    } else {
      // Multi-line plugins — add after the opening bracket line
      const indent = line.match(/^(\s*)/)?.[1] || "";
      const innerIndent = indent + "    ";
      lines.splice(pluginsLine + 1, 0, `${innerIndent}tricklePlugin(),`);
    }
  } else {
    // No plugins array found — need to add one
    // Find defineConfig({ and add plugins after it
    for (let i = 0; i < lines.length; i++) {
      if (/defineConfig\s*\(\s*\{/.test(lines[i])) {
        const indent = lines[i].match(/^(\s*)/)?.[1] || "";
        const innerIndent = indent + "    ";
        lines.splice(i + 1, 0, `${innerIndent}plugins: [tricklePlugin()],`);
        break;
      }
    }
  }

  fs.writeFileSync(configPath, lines.join("\n"), "utf-8");
  return true;
}

function updateNextConfig(dir: string): boolean {
  // Look for next.config.js, next.config.mjs, next.config.ts
  const candidates = ["next.config.js", "next.config.mjs", "next.config.ts"];
  let configFile: string | null = null;
  for (const c of candidates) {
    if (fs.existsSync(path.join(dir, c))) {
      configFile = c;
      break;
    }
  }

  if (!configFile) return false;

  const configPath = path.join(dir, configFile);
  const content = fs.readFileSync(configPath, "utf-8");

  // Already has withTrickle
  if (content.includes("withTrickle")) return false;

  // Detect config style and wrap
  const isESM = configFile.endsWith(".mjs") || configFile.endsWith(".ts") || content.includes("export default");

  if (isESM) {
    // ESM: add import and wrap export
    const importLine = `import { withTrickle } from 'trickle-observe/next-plugin';\n`;
    // Wrap: export default X → export default withTrickle(X)
    const updated = importLine + content.replace(
      /export\s+default\s+({[\s\S]*?}|[a-zA-Z_$][a-zA-Z0-9_$]*)/,
      (match, configExpr) => `export default withTrickle(${configExpr})`,
    );
    fs.writeFileSync(configPath, updated, "utf-8");
  } else {
    // CJS: add require and wrap module.exports
    const requireLine = `const { withTrickle } = require('trickle-observe/next-plugin');\n`;
    // Wrap: module.exports = X → module.exports = withTrickle(X)
    const updated = requireLine + content.replace(
      /module\.exports\s*=\s*([\s\S]*?)(?=;\s*$|$)/m,
      (match, configExpr) => `module.exports = withTrickle(${configExpr.trimEnd()})`,
    );
    fs.writeFileSync(configPath, updated, "utf-8");
  }

  return true;
}

function updateGitignore(dir: string): boolean {
  const giPath = path.join(dir, ".gitignore");
  let content = "";

  if (fs.existsSync(giPath)) {
    content = fs.readFileSync(giPath, "utf-8");
    if (content.includes(".trickle")) {
      return false; // Already has it
    }
  }

  const addition = content.endsWith("\n") || content === ""
    ? ".trickle/\n"
    : "\n.trickle/\n";

  fs.writeFileSync(giPath, content + addition, "utf-8");
  return true;
}

function createClaudeMd(dir: string, info: ProjectInfo): boolean {
  const claudePath = path.join(dir, "CLAUDE.md");

  // Don't overwrite existing CLAUDE.md
  if (fs.existsSync(claudePath)) {
    // Check if trickle section already exists
    const existing = fs.readFileSync(claudePath, "utf-8");
    if (existing.includes("trickle")) return false;

    // Append trickle section to existing CLAUDE.md
    const section = generateTrickleSection(info);
    fs.writeFileSync(claudePath, existing.trimEnd() + "\n\n" + section, "utf-8");
    return true;
  }

  // Create new CLAUDE.md with trickle instructions
  const runCmd = info.isPython
    ? `trickle run python ${info.entryFile || "app.py"}`
    : `trickle run node ${info.entryFile || "app.js"}`;

  const exampleFile = info.isPython
    ? (info.entryFile || "app.py")
    : (info.entryFile || "src/index.ts");

  const content = `# Project Instructions

## Runtime Observability with trickle

This project uses **trickle** for runtime observability. Instead of adding console.log/print
statements, use trickle to capture and query runtime data automatically.

### Quick Start

\`\`\`bash
# Capture runtime data (zero code changes)
${runCmd}

# Get a complete overview (errors, queries, alerts, root causes)
trickle summary

# Understand a specific file
trickle explain ${exampleFile}

# Run tests with observability
trickle test

# Performance analysis
trickle flamegraph
\`\`\`

### Agent Debugging Workflow

1. **Get overview**: \`trickle summary\` — status, errors, N+1 queries, root causes, fix recommendations
2. **Understand a file**: \`trickle explain ${exampleFile}\` — functions, call graph, data flow, queries, variables
3. **Debug errors**: \`trickle why\` — causal chain: error → call trace → variables → LLM reasoning
4. **Fix & verify**: \`trickle verify --baseline\` → fix code → \`${runCmd}\` → \`trickle verify\`
5. **Evaluate quality**: \`trickle eval\` — A-F reliability score (completion, errors, cost, tools, latency)
6. **Check security**: \`trickle security\` — prompt injection, privilege escalation, data exfiltration
7. **LLM costs**: \`trickle cost-report\` — cost breakdown by provider/model with budget checking
8. **Compliance**: \`trickle audit --compliance\` — risk classification, decision lineage, audit trail

### MCP Server (recommended for Claude Code)

Add to \`.claude/settings.json\` or \`claude_desktop_config.json\`:

\`\`\`json
{
  "mcpServers": {
    "trickle": {
      "command": "npx",
      "args": ["trickle-cli", "mcp-server"]
    }
  }
}
\`\`\`

Key MCP tools (38 total):

| Tool | Use for |
|------|---------|
| \`get_recommended_actions\` | Start here — tells you exactly what to do next |
| \`get_last_run_summary\` | Complete overview: errors, queries, alerts, root causes |
| \`why\` | Causal debugging: trace back from error to root cause |
| \`explain_file\` | Understand a file: functions, call graph, data flow, queries |
| \`run_tests\` | Run tests with structured pass/fail + runtime context |
| \`get_flamegraph\` | Performance hotspots sorted by execution time |
| \`get_llm_calls\` | LLM API calls with tokens, cost, latency |
| \`get_agent_trace\` | Agent execution tree with parent-child relationships |
| \`get_mcp_tool_calls\` | MCP tool invocations with latency and direction |
| \`get_cost_report\` | Cost breakdown by provider/model with budget check |
| \`save_baseline\` / \`compare_with_baseline\` | Before/after comparison for fix verification |

### What trickle Captures (automatically, zero config)

- **Functions**: signatures, params, return types, timing, sample I/O
- **Variables**: types + runtime values at each line
- **Database queries**: SQL text, duration, row count (pg, mysql2, sqlite3, Prisma, SQLAlchemy, Django ORM)
- **Errors**: with stack trace + nearby variable values
- **Logs**: winston, pino, bunyan (JS); logging, loguru, structlog (Python)
- **HTTP requests**: fetch/requests calls with status + latency
- **Call traces**: execution flow with parent-child relationships
- **LLM calls**: OpenAI, Anthropic, Gemini — model, tokens, cost, latency (auto-detected)
- **Agent workflows**: LangChain, CrewAI, Claude Agent SDK, OpenAI Agents SDK (auto-detected)
- **MCP tool calls**: tool name, arguments, response, latency, direction
- **Memory**: RSS + heap snapshots
`;

  fs.writeFileSync(claudePath, content, "utf-8");
  return true;
}

function generateTrickleSection(info: ProjectInfo): string {
  const runCmd = info.isPython
    ? `trickle run python ${info.entryFile || "app.py"}`
    : `trickle run node ${info.entryFile || "app.js"}`;

  return `## Runtime Observability with trickle

Use \`trickle summary\` for a complete overview, \`trickle explain <file>\` to understand a file,
and \`trickle test\` for tests with runtime context. Refresh data: \`${runCmd}\`

MCP server config (for \`.claude/settings.json\`):
\`\`\`json
{ "mcpServers": { "trickle": { "command": "npx", "args": ["trickle-cli", "mcp-server"] } } }
\`\`\`

Key tools: \`get_recommended_actions\` (start here), \`get_last_run_summary\`, \`explain_file\`,
\`run_tests\`, \`get_flamegraph\`, \`get_errors\`, \`save_baseline\`/\`compare_with_baseline\`.
`;
}

export async function initCommand(opts: InitOptions): Promise<void> {
  const dir = path.resolve(opts.dir || ".");

  console.log("");
  console.log(chalk.bold("  trickle init"));
  console.log("");

  // Step 1: Detect project
  const info = detectProject(dir, opts.python === true);

  if (!info.hasPackageJson && !info.isPython) {
    console.log(chalk.yellow("  No package.json or Python project detected."));
    console.log(chalk.gray("  Run this command from your project root.\n"));
    process.exit(1);
  }

  const lang = info.isPython ? "Python" : "Node.js";
  console.log(chalk.gray(`  Detected: ${lang} project${info.framework ? ` (${info.framework})` : ""}`));
  if (info.entryFile) {
    console.log(chalk.gray(`  Entry: ${info.entryFile}`));
  }
  console.log("");

  // Step 2: Create .tricklerc.json
  const configCreated = createTrickleConfig(dir, info);
  if (configCreated) {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".tricklerc.json")} — project config`);
  } else {
    console.log(`  ${chalk.gray("-")} .tricklerc.json already exists`);
  }

  // Step 3: Create .trickle directory
  const trickleDir = ensureTrickleDir(dir);
  console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/")} directory`);

  // Step 3: Write initial type files
  writeInitialTypes(trickleDir, info.isPython);
  if (info.isPython) {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/types.pyi")} (type stubs)`);
  } else {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/types.d.ts")} (type declarations)`);
    console.log(`  ${chalk.green("+")} Created ${chalk.bold(".trickle/api-client.ts")} (typed API client)`);
  }

  // Step 4: Update tsconfig.json
  if (!info.isPython) {
    const tsUpdated = updateTsConfig(dir, info);
    if (tsUpdated) {
      if (info.hasTsConfig) {
        console.log(`  ${chalk.green("~")} Updated ${chalk.bold("tsconfig.json")} — added .trickle to include`);
      } else {
        console.log(`  ${chalk.green("+")} Created ${chalk.bold("tsconfig.json")} with .trickle included`);
      }
    } else {
      console.log(`  ${chalk.gray("-")} tsconfig.json already includes .trickle`);
    }
  }

  // Step 5: Update vitest/vite config with tricklePlugin (also handles Remix which uses Vite)
  if (!info.isPython && info.framework !== "next") {
    const vitestUpdated = updateVitestConfig(dir);
    if (vitestUpdated) {
      console.log(`  ${chalk.green("~")} Updated ${chalk.bold("vite.config.ts")} — added tricklePlugin() for variable tracing`);
    }
  }

  // Step 5b: Update next.config.js with withTrickle
  if (info.framework === "next") {
    const nextUpdated = updateNextConfig(dir);
    if (nextUpdated) {
      console.log(`  ${chalk.green("~")} Updated ${chalk.bold("next.config.js")} — wrapped with withTrickle() for variable tracing`);
    }
  }

  // Step 6: Update package.json scripts
  if (info.hasPackageJson) {
    const { scriptsAdded } = updatePackageJson(dir, info);
    if (scriptsAdded.length > 0) {
      for (const name of scriptsAdded) {
        console.log(`  ${chalk.green("+")} Added npm script: ${chalk.bold(name)}`);
      }
    }
  }

  // Step 7: Update .gitignore
  const giUpdated = updateGitignore(dir);
  if (giUpdated) {
    console.log(`  ${chalk.green("~")} Updated ${chalk.bold(".gitignore")} — added .trickle/`);
  }

  // Step 8: Create CLAUDE.md for AI agent integration
  const claudeCreated = createClaudeMd(dir, info);
  if (claudeCreated) {
    console.log(`  ${chalk.green("+")} Created ${chalk.bold("CLAUDE.md")} — AI agent instructions for debugging with trickle`);
  }

  // Step 8b: Create .claude/settings.json with MCP server config
  const claudeSettingsDir = path.join(dir, ".claude");
  const claudeSettingsPath = path.join(claudeSettingsDir, "settings.json");
  if (!fs.existsSync(claudeSettingsPath)) {
    try {
      if (!fs.existsSync(claudeSettingsDir)) fs.mkdirSync(claudeSettingsDir, { recursive: true });
      const settings: any = {};
      // Check if settings already exist and merge
      if (fs.existsSync(claudeSettingsPath)) {
        try { Object.assign(settings, JSON.parse(fs.readFileSync(claudeSettingsPath, "utf-8"))); } catch {}
      }
      if (!settings.mcpServers?.trickle) {
        settings.mcpServers = settings.mcpServers || {};
        settings.mcpServers.trickle = { command: "npx", args: ["trickle-cli", "mcp-server"] };
        fs.writeFileSync(claudeSettingsPath, JSON.stringify(settings, null, 2) + "\n", "utf-8");
        console.log(`  ${chalk.green("+")} Created ${chalk.bold(".claude/settings.json")} — MCP server config for Claude Code`);
      }
    } catch {}
  } else {
    // Check if trickle MCP is already configured
    try {
      const existing = JSON.parse(fs.readFileSync(claudeSettingsPath, "utf-8"));
      if (!existing.mcpServers?.trickle) {
        existing.mcpServers = existing.mcpServers || {};
        existing.mcpServers.trickle = { command: "npx", args: ["trickle-cli", "mcp-server"] };
        fs.writeFileSync(claudeSettingsPath, JSON.stringify(existing, null, 2) + "\n", "utf-8");
        console.log(`  ${chalk.green("~")} Updated ${chalk.bold(".claude/settings.json")} — added trickle MCP server`);
      }
    } catch {}
  }

  // Step 9: Print next steps
  console.log("");
  console.log(chalk.bold("  Next steps:"));
  console.log("");

  if (info.framework === "vite" || info.framework === "remix" || info.framework === "next") {
    // React/Vite/Remix/Next.js — just run the dev server
    const devCmd = info.framework === "next" ? "next dev" : "npm run dev";
    console.log(chalk.white("  1. Install the VSCode extension:"));
    console.log(chalk.cyan("     code --install-extension yiheinchai.trickle-vscode"));
    console.log("");
    console.log(chalk.white("  2. Start your dev server as usual:"));
    console.log(chalk.cyan(`     ${devCmd}`));
    console.log("");
    console.log(chalk.white("  3. Open any .tsx file in VSCode — inline hints show variable values,"));
    console.log(chalk.white("     component render counts, hook invocations, and state updates."));
    console.log(chalk.white("     Values update live as you interact with your app."));
  } else {
    const entryFile = info.entryFile || (info.isPython ? "app.py" : "app.js");
    console.log(chalk.white("  1. Run your app with trickle (one command does everything):"));
    console.log(chalk.cyan(`     trickle run ${entryFile}`));
    console.log("");
    console.log(chalk.white("  2. Install the VSCode extension for inline hints:"));
    console.log(chalk.cyan("     code --install-extension yiheinchai.trickle-vscode"));
    console.log("");
    console.log(chalk.white("  3. That's it! trickle auto-detects the runtime, observes types,"));
    console.log(chalk.white("     and generates stubs from .tricklerc.json settings."));
  }

  console.log("");
  console.log(chalk.gray("  After running, explore your data:"));
  console.log(chalk.gray("     trickle summary           — errors, queries, root causes, fix recommendations"));
  console.log(chalk.gray("     trickle explain <file>    — functions, call graph, data flow, variables"));
  console.log(chalk.gray("     trickle test              — run tests with observability (jest/vitest/pytest)"));
  console.log(chalk.gray("     trickle flamegraph        — interactive performance hotspot visualization"));
  console.log(chalk.gray("     trickle doctor            — health check with recommended next actions"));

  console.log("");
}
