// Auto-generated by trickle from runtime type observations
// Generated at 2026-03-12T09:51:12.160Z
// Do not edit manually — re-run `trickle codegen` to update

/**
 * Output type for `main` — test-run-app module, observed in node, 49m ago
 */
export type MainOutput = undefined;

/**
 * @example
 * // Sample input:
 * []
 */
export declare function main(): MainOutput;
