// Auto-generated by trickle/auto from runtime observations
// Generated at 2026-03-12T09:09:07.755Z
// Do not edit — types update automatically as your code runs

export declare class Calculator {
  add(a: number, b: number): {
    result: number;
    operation: string;
  };
  multiply(a: number, b: number): {
    result: number;
    operation: string;
  };
  square(x: number): {
    result: number;
    input: number;
  };
}

export declare class Formatter {
  formatName(first: string, last: string): {
    display: string;
    first: string;
    last: string;
  };
  formatCurrency(amount: number, currency: string): {
    formatted: string;
    amount: number;
    currency: string;
  };
}
