// Auto-generated by trickle from runtime type observations
// Generated at 2026-03-12T09:51:12.160Z
// Do not edit manually — re-run `trickle codegen` to update

/**
 * Input type for `parseConfig` — test-run-helpers module, observed in node, 49m ago
 */
export interface ParseConfigInput {
  host: string;
  port: number;
  debug: boolean;
}

/**
 * Output type for `parseConfig` — test-run-helpers module, observed in node, 49m ago
 */
export interface ParseConfigOutput {
  host: string;
  port: number;
  debug: boolean;
  retries: number;
}

/**
 * @example
 * // Sample input:
 * [
 *   {
 *     "host": "api.example.com",
 *     "port": 8080,
 *     "debug": true
 *   }
 * ]
 * // Sample output:
 * {
 *   "host": "api.example.com",
 *   "port": 8080,
 *   "debug": true,
 *   "retries": 3
 * }
 */
export declare function parseConfig(input: ParseConfigInput): ParseConfigOutput;

/**
 * Output type for `processItems` — test-run-helpers module, observed in node, 49m ago
 */
export type ProcessItemsOutput = {
  id: number;
  name: string;
  processed: boolean;
  timestamp: string;
}[];

/**
 * @example
 * // Sample input:
 * [
 *   [
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]"
 *     },
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]"
 *     },
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]"
 *     }
 *   ]
 * ]
 * // Sample output:
 * [
 *   {
 *     "id": 1,
 *     "name": "WIDGET",
 *     "processed": true,
 *     "timestamp": "2026-03-12T09:01:39.831Z"
 *   },
 *   {
 *     "id": 2,
 *     "name": "GADGET",
 *     "processed": true,
 *     "timestamp": "2026-03-12T09:01:39.831Z"
 *   },
 *   {
 *     "id": 3,
 *     "name": "DOOHICKEY",
 *     "processed": true,
 *     "timestamp": "2026-03-12T09:01:39.831Z"
 *   }
 * ]
 */
export declare function processItems(arg0: {
  id: number;
  name: string;
}[]): ProcessItemsOutput;

/**
 * Output type for `fetchData` — test-run-helpers module, observed in node, 23m ago
 */
export interface FetchDataOutput {
  status: number;
  data: {
    users: unknown[];
  };
  headers: {
    content-type: string;
  };
}

/**
 * @example
 * // Sample input:
 * [
 *   "https://api.example.com/users"
 * ]
 * // Sample output:
 * {
 *   "status": 200,
 *   "data": {
 *     "users": [
 *       "[truncated]",
 *       "[truncated]"
 *     ]
 *   },
 *   "headers": {
 *     "content-type": "application/json"
 *   }
 * }
 */
export declare function fetchData(arg0: string): FetchDataOutput;

/**
 * Input type for `transformResponse` — test-run-helpers module, observed in node, 23m ago
 */
export interface TransformResponseInput {
  status: number;
  data: {
    users: unknown[];
  };
  headers: {
    content-type: string;
  };
}

/**
 * Output type for `transformResponse` — test-run-helpers module, observed in node, 23m ago
 */
export interface TransformResponseOutput {
  count: number;
  names: string[];
  fetchedAt: string;
}

/**
 * @example
 * // Sample input:
 * [
 *   {
 *     "status": 200,
 *     "data": {
 *       "users": "[truncated]"
 *     },
 *     "headers": {
 *       "content-type": "[truncated]"
 *     }
 *   }
 * ]
 * // Sample output:
 * {
 *   "count": 2,
 *   "names": [
 *     "Alice",
 *     "Bob"
 *   ],
 *   "fetchedAt": "2026-03-12T09:27:50.741Z"
 * }
 */
export declare function transformResponse(input: TransformResponseInput): TransformResponseOutput;

/**
 * Output type for `calculateStats` — test-run-helpers module, observed in node, 49m ago
 */
export interface CalculateStatsOutput {
  sum: number;
  avg: number;
  min: number;
  max: number;
  count: number;
}

/**
 * @example
 * // Sample input:
 * [
 *   [
 *     10,
 *     20,
 *     30,
 *     40,
 *     50
 *   ]
 * ]
 * // Sample output:
 * {
 *   "sum": 150,
 *   "avg": 30,
 *   "min": 10,
 *   "max": 50,
 *   "count": 5
 * }
 */
export declare function calculateStats(arg0: number[]): CalculateStatsOutput;
