// Auto-generated by trickle from runtime type observations
// Generated at 2026-03-12T09:51:12.160Z
// Do not edit manually — re-run `trickle codegen` to update

export interface ProcessOrderInputItems {
  name: string;
  price: number;
  quantity: number;
}

/**
 * Input type for `processOrder` — test-e2e module, observed in node, 41m ago
 */
export interface ProcessOrderInput {
  id: string;
  customer: {
    name: string;
    email: string;
  };
  items: ProcessOrderInputItems[];
}

/**
 * Output type for `processOrder` — test-e2e module, observed in node, 41m ago
 */
export interface ProcessOrderOutput {
  orderId: string;
  customer: string;
  total: number;
  tax: number;
  grandTotal: number;
  status: string;
}

/**
 * @example
 * // Sample input:
 * [
 *   {
 *     "id": "ORD-123",
 *     "customer": {
 *       "name": "[truncated]",
 *       "email": "[truncated]"
 *     },
 *     "items": [
 *       "[truncated]",
 *       "[truncated]"
 *     ]
 *   }
 * ]
 * // Sample output:
 * {
 *   "orderId": "ORD-123",
 *   "customer": "Alice",
 *   "total": 109.97,
 *   "tax": 10.997,
 *   "grandTotal": 120.967,
 *   "status": "processed"
 * }
 */
export declare function processOrder(input: ProcessOrderInput): ProcessOrderOutput;

export interface GetUserArg1 {
  includeRoles: boolean;
}

/**
 * Output type for `getUser` — test-e2e module, observed in node, 41m ago
 */
export interface GetUserOutput {
  id: string;
  name: string;
  email: string;
  roles: string[];
  metadata: {
    lastLogin: string;
    loginCount: number;
  };
}

/**
 * @example
 * // Sample input:
 * [
 *   "usr-456",
 *   {
 *     "includeRoles": true
 *   }
 * ]
 * // Sample output:
 * {
 *   "id": "usr-456",
 *   "name": "John Doe",
 *   "email": "john@example.com",
 *   "roles": [
 *     "admin",
 *     "user"
 *   ],
 *   "metadata": {
 *     "lastLogin": "2026-03-12T09:09:15.668Z",
 *     "loginCount": 42
 *   }
 * }
 */
export declare function getUser(arg0: string, arg1: GetUserArg1): GetUserOutput;

/**
 * Input type for `validatePayment` — test-e2e module, observed in node, 41m ago
 */
export interface ValidatePaymentInput {
  amount: number;
  method: string;
}

/**
 * Output type for `validatePayment` — test-e2e module, observed in node, 41m ago
 */
export type ValidatePaymentOutput = unknown;

/**
 * @example
 * // Sample input:
 * [
 *   {
 *     "amount": 100,
 *     "method": "credit"
 *   }
 * ]
 */
export declare function validatePayment(input: ValidatePaymentInput): ValidatePaymentOutput;
