# Auto-generated by trickle from runtime type observations
# Generated at 2026-03-12T09:51:12.160Z
# Do not edit manually — re-run `trickle codegen --python` to update

from typing import Any, Awaitable, Callable, Dict, List, Optional, Set, Tuple, TypedDict, Union


# ProcessOrder — test-e2e module, observed in node, 41m ago
class ProcessOrderInputCustomer(TypedDict):
    name: str
    email: str


class ProcessOrderInputItems(TypedDict):
    name: str
    price: float
    quantity: float


class ProcessOrderInput(TypedDict):
    id: str
    customer: ProcessOrderInputCustomer
    items: List[ProcessOrderInputItems]


class ProcessOrderOutput(TypedDict):
    order_id: str
    customer: str
    total: float
    tax: float
    grand_total: float
    status: str


# GetUser — test-e2e module, observed in node, 41m ago
class GetUserArgsArg1(TypedDict):
    include_roles: bool


class GetUserArgs(TypedDict):
    arg0: str
    arg1: GetUserArgsArg1


class GetUserOutputMetadata(TypedDict):
    last_login: str
    login_count: float


class GetUserOutput(TypedDict):
    id: str
    name: str
    email: str
    roles: List[str]
    metadata: GetUserOutputMetadata


# ValidatePayment — test-e2e module, observed in node, 41m ago
class ValidatePaymentInput(TypedDict):
    amount: float
    method: str


ValidatePaymentOutput = Any
