// Auto-generated by trickle from runtime type observations
// Generated at 2026-03-12T09:51:12.160Z
// Do not edit manually — re-run `trickle codegen` to update

export interface GetApiProductsOutputProducts {
  id: number;
  name: string;
  price: number;
  category: string;
}

/**
 * Output type for `GET /api/products` — express module, observed in node, 40m ago
 */
export interface GetApiProductsOutput {
  products: GetApiProductsOutputProducts[];
  total: number;
  page: number;
}

/**
 * @example
 * // Sample input:
 * {}
 * // Sample output:
 * {
 *   "products": [
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]",
 *       "price": "[truncated]",
 *       "category": "[truncated]"
 *     },
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]",
 *       "price": "[truncated]",
 *       "category": "[truncated]"
 *     },
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]",
 *       "price": "[truncated]",
 *       "category": "[truncated]"
 *     }
 *   ],
 *   "total": 3,
 *   "page": 1
 * }
 */
export declare function getApiProducts(): GetApiProductsOutput;

/**
 * Input type for `GET /api/products/:id` — express module, observed in node, 40m ago
 */
export interface GetApiProductsIdInput {
  id: string;
}

/**
 * Output type for `GET /api/products/:id` — express module, observed in node, 40m ago
 */
export interface GetApiProductsIdOutput {
  id: number;
  name: string;
  price: number;
  category: string;
  description: string;
  reviews: {
    rating: number;
    comment: string;
  }[];
}

/**
 * @example
 * // Sample input:
 * {
 *   "params": {
 *     "id": "1"
 *   }
 * }
 * // Sample output:
 * {
 *   "id": 1,
 *   "name": "Widget",
 *   "price": 29.99,
 *   "category": "electronics",
 *   "description": "A fine widget for all your widgeting needs",
 *   "reviews": [
 *     {
 *       "rating": "[truncated]",
 *       "comment": "[truncated]"
 *     },
 *     {
 *       "rating": "[truncated]",
 *       "comment": "[truncated]"
 *     }
 *   ]
 * }
 */
export declare function getApiProductsId(input: GetApiProductsIdInput): GetApiProductsIdOutput;

export interface PostApiCartAddOutputItems {
  productId: number;
  quantity: number;
  price: number;
}

/**
 * Input type for `POST /api/cart/add` — express module, observed in node, 40m ago
 */
export interface PostApiCartAddInput {
  productId: number;
  quantity: number;
}

/**
 * Output type for `POST /api/cart/add` — express module, observed in node, 40m ago
 */
export interface PostApiCartAddOutput {
  cartId: string;
  items: PostApiCartAddOutputItems[];
  subtotal: number;
}

/**
 * @example
 * // Sample input:
 * {
 *   "body": {
 *     "productId": 1,
 *     "quantity": 2
 *   }
 * }
 * // Sample output:
 * {
 *   "cartId": "CART-12345",
 *   "items": [
 *     {
 *       "productId": "[truncated]",
 *       "quantity": "[truncated]",
 *       "price": "[truncated]"
 *     }
 *   ],
 *   "subtotal": 59.98
 * }
 */
export declare function postApiCartAdd(input: PostApiCartAddInput): PostApiCartAddOutput;

/**
 * Input type for `DELETE /api/cart/:cartId` — express module, observed in node, 40m ago
 */
export interface DeleteApiCartCartIdInput {
  cartId: string;
}

/**
 * Output type for `DELETE /api/cart/:cartId` — express module, observed in node, 40m ago
 */
export interface DeleteApiCartCartIdOutput {
  deleted: boolean;
  cartId: string;
}

/**
 * @example
 * // Sample input:
 * {
 *   "params": {
 *     "cartId": "CART-999"
 *   }
 * }
 * // Sample output:
 * {
 *   "deleted": true,
 *   "cartId": "CART-999"
 * }
 */
export declare function deleteApiCartCartId(input: DeleteApiCartCartIdInput): DeleteApiCartCartIdOutput;

export interface GetApiUsersOutputUsers {
  id: number;
  name: string;
  email: string;
  role: string;
}

/**
 * Output type for `GET /api/users` — express module, observed in node, 41m ago
 */
export interface GetApiUsersOutput {
  users: GetApiUsersOutputUsers[];
  total: number;
}

/**
 * @example
 * // Sample input:
 * {}
 * // Sample output:
 * {
 *   "users": [
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]",
 *       "email": "[truncated]",
 *       "role": "[truncated]"
 *     },
 *     {
 *       "id": "[truncated]",
 *       "name": "[truncated]",
 *       "email": "[truncated]",
 *       "role": "[truncated]"
 *     }
 *   ],
 *   "total": 2
 * }
 */
export declare function getApiUsers(): GetApiUsersOutput;

/**
 * Input type for `GET /api/users/:id` — express module, observed in node, 41m ago
 */
export interface GetApiUsersIdInput {
  id: string;
}

/**
 * Output type for `GET /api/users/:id` — express module, observed in node, 41m ago
 */
export interface GetApiUsersIdOutput {
  id: number;
  name: string;
  email: string;
  role: string;
  metadata: {
    lastLogin: string;
    loginCount: number;
  };
}

/**
 * @example
 * // Sample input:
 * {
 *   "params": {
 *     "id": "1"
 *   }
 * }
 * // Sample output:
 * {
 *   "id": 1,
 *   "name": "Alice",
 *   "email": "alice@example.com",
 *   "role": "admin",
 *   "metadata": {
 *     "lastLogin": "2026-03-10T10:00:00Z",
 *     "loginCount": 42
 *   }
 * }
 */
export declare function getApiUsersId(input: GetApiUsersIdInput): GetApiUsersIdOutput;

export interface PostApiOrdersInputItems {
  name: string;
  price: number;
  quantity: number;
}

/**
 * Input type for `POST /api/orders` — express module, observed in node, 41m ago
 */
export interface PostApiOrdersInput {
  customer: string;
  items: PostApiOrdersInputItems[];
}

/**
 * Output type for `POST /api/orders` — express module, observed in node, 41m ago
 */
export interface PostApiOrdersOutput {
  orderId: string;
  customer: string;
  total: number;
  status: string;
}

/**
 * @example
 * // Sample input:
 * {
 *   "body": {
 *     "customer": "Alice",
 *     "items": [
 *       "[truncated]",
 *       "[truncated]"
 *     ]
 *   }
 * }
 * // Sample output:
 * {
 *   "orderId": "ORD-1773306555867",
 *   "customer": "Alice",
 *   "total": 109.97,
 *   "status": "created"
 * }
 */
export declare function postApiOrders(input: PostApiOrdersInput): PostApiOrdersOutput;

export interface PutApiUsersIdBody {
  name: string;
  email: string;
}

export interface PutApiUsersIdParams {
  id: string;
}

/**
 * Output type for `PUT /api/users/:id` — express module, observed in node, 41m ago
 */
export interface PutApiUsersIdOutput {
  id: number;
  name: string;
  email: string;
  updated: boolean;
}

/**
 * @example
 * // Sample input:
 * {
 *   "body": {
 *     "name": "Alice Updated",
 *     "email": "alice2@example.com"
 *   },
 *   "params": {
 *     "id": "1"
 *   }
 * }
 * // Sample output:
 * {
 *   "id": 1,
 *   "name": "Alice Updated",
 *   "email": "alice2@example.com",
 *   "updated": true
 * }
 */
export declare function putApiUsersId(body: PutApiUsersIdBody, params: PutApiUsersIdParams): PutApiUsersIdOutput;

/**
 * Input type for `POST /api/cart` — express module, observed in node, 41m ago
 */
export interface PostApiCartInput {
  productId: number;
  quantity: number;
}

/**
 * Output type for `POST /api/cart` — express module, observed in node, 41m ago
 */
export interface PostApiCartOutput {
  cartId: string;
  productId: number;
  quantity: number;
  added: boolean;
}

/**
 * @example
 * // Sample input:
 * {
 *   "body": {
 *     "productId": 1,
 *     "quantity": 3
 *   }
 * }
 * // Sample output:
 * {
 *   "cartId": "CART-1773306558041",
 *   "productId": 1,
 *   "quantity": 3,
 *   "added": true
 * }
 */
export declare function postApiCart(input: PostApiCartInput): PostApiCartOutput;
